services:
  kakua-jupyter-lab:
    image: quay.io/jupyter/base-notebook
    volumes:
      - ./research:/research
    ports:
      - 8445:8445
    env_file:
      - fileName: .env_file
    command: start-notebook.py --port 8445 --notebook-dir="/research" --NotebookApp.token=$NOTEBOOK_TOKEN
  kakua-code-server:
    image: lscr.io/linuxserver/code-server:latest
    build:
        context: "./"
    container_name: code-server
    env_file:
      - fileName: .env_file
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - PASSWORD=$NOTEBOOK_PASSWD
      - DEFAULT_WORKSPACE=/research
      - PWA_APPNAME=kakua-code-server
    volumes:
      - ./config:/config
      - ./research:/research
    ports:
      - 8443:8443
    restart: unless-stopped
