version: 2.1

jobs:
  build-and-deploy:
    machine:
      image: ubuntu-2204:2024.11.1
    steps:
      - checkout
      - run:
          name: Add server to known_hosts
          command: ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "$FINGERPRINT"
      - run:
          name: Build and Deploy Docker image on remote server
          command: |
            ssh $SSH_USER@$SSH_HOST "
            cd $APP_PATH && git pull origin main &&
            touch .env_file &&
            echo 'NOTEBOOK_TOKEN=$NOTEBOOK_TOKEN' > .env_file &&
            echo 'NOTEBOOK_PASSWD=$NOTEBOOK_PASSWD' >> .env_file &&
            echo 'PUID=$(id -u)' >> .env_file &&
            echo 'PGID=$(id -g)' >> .env_file &&
            docker compose down --remove-orphans &&
            docker compose build &&
            docker compose up -d --env-file .env_file"
workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy